### ISSUE TITLE
Uncaught ReferenceError: Circle is not defined

### ISSUE THREAD

**Issue by ajeetvarma** [seal789ie/react-fabricjs#5]
I installed the react-fabric by command "npm install react-fabricjs --save"  and use 

import {Canvas,Circle, Image, Path, Text} from 'react-fabricjs';

This is not working and following error in console **Uncaught ReferenceError: Circle is not defined** is comming . i do't know what am i doing wrong ..

I have need of help regarding this so that i can use this library . 

Thanks in Advanced ..

**Comment by seal789ie** [comment]
it has been fixed. Please update to v0.1.5, and try again.
thank you : )

**Comment by ajeetvarma** [comment]
Now it works ..
Thanks a lot !

**Comment by rlaucik** [comment]
Oh I haven't noticed that release, I installed it just yesterday so I was looking for possibly helpful commits in other branches or forks and I was missing the most obvious solution 😳
It works now and now I am going to see what this baby can do.
Thank you!
