### ISSUE TITLE
Doesn't seem to mount

### ISSUE THREAD

**Issue by greg-lightful** [seal789ie/react-fabricjs#6]
With just a Canvas element `<Canvas ref="canvas" width="1000" height="1000"></Canvas>` it renders fine... put if you put anything inside as per the example `<Circle />` etc you get an error about insertBefore

`Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

**Comment by greg-lightful** [comment]
Using React 15.0.2

**Comment by rlaucik** [comment]
Having the same problem. Did you found any workaround or temporary fix? Is it because of version of React? Or are we doing something wrong? (I guess not because also example from readme does not work)

**Comment by seal789ie** [comment]
This issue has been fixed in v0.1.6. try it again plz.
